// packages/sds-vue-components/src/App.vue
<script setup>
import { SdsButton, SdsAccordion, SdsAccordionItem } from "./index";

const handleClick = () => {
  window.alert("Button Clicked!");
};
</script>

<template>
  <div>
    <h1>Testing Vue Components</h1>
    <SdsButton variant="primary" @click="handleClick">Test!</SdsButton>
    <SdsAccordion>
      <SdsAccordionItem summary="Item 1"> test item 1</SdsAccordionItem>
      <SdsAccordionItem summary="Item 2"> test item 2</SdsAccordionItem>
      <SdsAccordionItem summary="Item 3"> test item 3</SdsAccordionItem>
    </SdsAccordion>
  </div>
</template>

// example-apps/sds-example-react/src/App.tsx
import {
  SdsAccordion,
  SdsAccordionItem,
  SdsButton,
} from 'sds-react-components';
import './App.css';

function App() {
  const handleClick = () => {
    window.alert('Button Clicked!');
  };

  return (
    <>
      <SdsButton variant='primary' onClick={handleClick}>
        Test!
      </SdsButton>
      <SdsAccordion>
        <SdsAccordionItem summary='Item 1'>
          This is an accordion item.
        </SdsAccordionItem>
        <SdsAccordionItem summary='Item 2'>
          This is another item.
        </SdsAccordionItem>
      </SdsAccordion>
    </>
  );
}

export default App;
